"""
Скрипт для заполнения базы данных тестовыми данными.
Запуск: python manage.py shell < populate_db.py
или: python populate_db.py (из папки проекта)
"""

import os
import sys
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'bookstore.settings')
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
django.setup()

from django.contrib.auth.models import User
from store.models import Category, Author, Book

print("Создаём суперпользователя...")
if not User.objects.filter(username='admin').exists():
    User.objects.create_superuser('admin', 'admin@example.com', 'admin123')
    print("  Суперпользователь создан: admin / admin123")
else:
    print("  Суперпользователь уже существует.")

print("\nСоздаём категории...")
categories_data = [
    ('Классическая литература', 'klassicheskaya-literatura', 'Произведения великих писателей прошлого'),
    ('Современная проза', 'sovremennaya-proza', 'Лучшие романы современных авторов'),
    ('Детективы', 'detektivy', 'Захватывающие детективные истории'),
    ('Фантастика', 'fantastika', 'Научная фантастика и фэнтези'),
    ('Детская литература', 'detskaya-literatura', 'Книги для детей и подростков'),
    ('Учебники', 'uchebniki', 'Образовательная литература'),
    ('Психология', 'psihologiya', 'Книги по психологии и саморазвитию'),
    ('История', 'istoriya', 'Исторические произведения и документалистика'),
]

categories = {}
for name, slug, desc in categories_data:
    cat, created = Category.objects.get_or_create(slug=slug, defaults={'name': name, 'description': desc})
    categories[slug] = cat
    print(f"  {'Создана' if created else 'Уже есть'}: {name}")

print("\nСоздаём авторов...")
authors_data = [
    ('Лев', 'Толстой', 'Великий русский писатель (1828–1910), автор "Войны и мира" и "Анны Карениной". Проповедовал нравственное самосовершенствование и ненасилие. Один из величайших романистов в истории мировой литературы.'),
    ('Фёдор', 'Достоевский', 'Русский писатель (1821–1881), мастер психологической прозы. Автор "Преступления и наказания", "Идиота", "Братьев Карамазовых". Исследовал темы страдания, веры и морали.'),
    ('Агата', 'Кристи', 'Знаменитая английская писательница (1890–1976), королева детективного жанра. Автор более 80 романов, в том числе историй о Эркюле Пуаро и мисс Марпл. Одна из самых издаваемых писателей в мире.'),
    ('Стивен', 'Кинг', 'Американский мастер ужасов и триллеров (род. 1947). Автор более 60 романов — "Оно", "Сияние", "Мизери". Продал свыше 350 миллионов книг по всему миру.'),
    ('Джоан', 'Роулинг', 'Британская писательница (род. 1965), автор серии о Гарри Поттере — одной из самых продаваемых книжных серий в истории. До успеха была матерью-одиночкой на пособии.'),
    ('Михаил', 'Булгаков', 'Русский писатель и драматург (1891–1940), автор "Мастера и Маргариты" — одного из самых читаемых романов XX века. Врач по образованию.'),
    ('Чингиз', 'Айтматов', 'Выдающийся кыргызский и советский писатель (1928–2008), писал на кыргызском и русском языках. Автор "Джамили", "Белого парохода", "Плахи". Его роман "Джамиля" Луи Арагон назвал "самой прекрасной повестью о любви в мировой литературе". Национальный символ Кыргызстана.'),
    ('Эрих Мария', 'Ремарк', 'Немецкий писатель (1898–1970), автор "На Западном фронте без перемен" — одного из самых пронзительных антивоенных романов в истории. Его книги были сожжены нацистами в 1933 году.'),
    ('Антон', 'Чехов', 'Русский писатель и драматург (1860–1904), мастер короткого рассказа. Автор пьес "Вишнёвый сад", "Три сестры", "Чайка". Врач по образованию, как и Булгаков.'),
    ('Александр', 'Пушкин', 'Основоположник современного русского литературного языка (1799–1837). Автор "Евгения Онегина", "Капитанской дочки", множества стихотворений. Погиб на дуэли в 37 лет.'),
    ('Джордж', 'Оруэлл', 'Британский писатель и публицист (1903–1950). Автор антиутопий "1984" и "Скотный двор". Критиковал тоталитаризм и политическую ложь. Его книги остаются актуальными по сей день.'),
    ('Борис', 'Акунин', 'Российский писатель (род. 1956), настоящее имя — Григорий Чхартишвили. Автор детективной серии о сыщике Эрасте Фандорине. Один из самых популярных современных авторов на русском языке.'),
    ('Токомбай', 'Абдумомунов', 'Кыргызский советский писатель и драматург (1918–1993). Народный писатель Кыргызской ССР. Автор романов и пьес о жизни кыргызского народа, лауреат Государственной премии СССР.'),
    ('Эрнест', 'Хемингуэй', 'Американский писатель (1899–1961), лауреат Нобелевской премии 1954 года. Автор "Старика и моря", "По ком звонит колокол". Известен лаконичным стилем письма — "теория айсберга".'),
    ('Франц', 'Кафка', 'Австрийский писатель (1883–1924), писал на немецком языке. Автор "Превращения" и "Процесса". Его произведения полны абсурда и экзистенциального страха — отсюда слово "кафкианский".'),
]

authors = {}
authors_list = []
for first, last, bio in authors_data:
    author, created = Author.objects.get_or_create(
        first_name=first, last_name=last,
        defaults={'bio': bio}
    )
    authors[f"{first} {last}"] = author
    authors_list.append(author)
    print(f"  {'Создан' if created else 'Уже есть'}: {first} {last}")

print("\nСоздаём книги...")
books_data = [
    {
        'title': 'Война и мир',
        'slug': 'voyna-i-mir',
        'author': authors['Лев Толстой'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Эпический роман-эпопея Льва Толстого, описывающий русское общество в эпоху войн с Наполеоном. Одно из величайших произведений мировой литературы.',
        'price': 850,
        'stock': 15,
        'pages': 1225,
        'year_published': 1869,
        'publisher': 'Эксмо',
        'language': 'Русский',
        'isbn': '978-5-04-089473-6',
        'featured': True,
    },
    {
        'title': 'Анна Каренина',
        'slug': 'anna-karenina',
        'author': authors['Лев Толстой'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Роман о трагической судьбе женщины в высшем свете, разрывающейся между долгом и любовью. Вечная история страсти и нравственного выбора.',
        'price': 750,
        'stock': 8,
        'pages': 864,
        'year_published': 1878,
        'publisher': 'Эксмо',
        'language': 'Русский',
        'isbn': '978-5-04-099877-0',
        'featured': False,
    },
    {
        'title': 'Преступление и наказание',
        'slug': 'prestuplenie-i-nakazanie',
        'author': authors['Фёдор Достоевский'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Философский роман о студенте Раскольникове, решившемся на убийство. Одно из самых известных произведений Достоевского.',
        'price': 650,
        'stock': 20,
        'pages': 672,
        'year_published': 1866,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-090823-4',
        'featured': True,
    },
    {
        'title': 'Идиот',
        'slug': 'idiot-dostoevsky',
        'author': authors['Фёдор Достоевский'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Роман о добром и наивном князе Мышкине, оказавшемся в жестоком мире петербургского общества. Размышления о природе добра и красоты.',
        'price': 580,
        'stock': 9,
        'pages': 640,
        'year_published': 1869,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-099123-7',
        'featured': False,
    },
    {
        'title': 'Братья Карамазовы',
        'slug': 'bratya-karamazovy',
        'author': authors['Фёдор Достоевский'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Последний роман Достоевского — глубокое философское исследование веры, сомнения, морали и семейных отношений. Многие считают его вершиной творчества писателя.',
        'price': 700,
        'stock': 11,
        'pages': 896,
        'year_published': 1880,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-099124-4',
        'featured': False,
    },
    {
        'title': 'Убийство в Восточном экспрессе',
        'slug': 'ubiystvo-v-vostochnom-ekspresse',
        'author': authors['Агата Кристи'],
        'category': categories['detektivy'],
        'description': 'Классический детектив с Эркюлем Пуаро. В поезде, застрявшем в снегах, найден убитый. Кто преступник среди двенадцати подозреваемых?',
        'price': 480,
        'stock': 25,
        'pages': 288,
        'year_published': 1934,
        'publisher': 'Эксмо',
        'language': 'Русский',
        'isbn': '978-5-04-106843-2',
        'featured': True,
    },
    {
        'title': 'Десять негритят',
        'slug': 'desyat-negrityat',
        'author': authors['Агата Кристи'],
        'category': categories['detektivy'],
        'description': 'Самый известный детектив Агаты Кристи. Десять человек приглашены на уединённый остров, и один за другим начинают погибать.',
        'price': 440,
        'stock': 20,
        'pages': 256,
        'year_published': 1939,
        'publisher': 'Эксмо',
        'language': 'Русский',
        'isbn': '978-5-04-107234-7',
        'featured': False,
    },
    {
        'title': 'Сияние',
        'slug': 'siyanie',
        'author': authors['Стивен Кинг'],
        'category': categories['fantastika'],
        'description': 'Роман ужасов о смотрителе отеля Overlook, изолированного в горах Колорадо зимой. Психологический триллер о безумии и сверхъестественном.',
        'price': 720,
        'stock': 10,
        'pages': 688,
        'year_published': 1977,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-119743-1',
        'featured': False,
    },
    {
        'title': 'Оно',
        'slug': 'ono-stiven-king',
        'author': authors['Стивен Кинг'],
        'category': categories['fantastika'],
        'description': 'Культовый роман ужасов о группе детей из города Дерри, столкнувшихся с древним злом в образе клоуна Пеннивайза.',
        'price': 890,
        'stock': 7,
        'pages': 1376,
        'year_published': 1986,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-119744-8',
        'featured': True,
    },
    {
        'title': 'Мизери',
        'slug': 'mizeri-king',
        'author': authors['Стивен Кинг'],
        'category': categories['fantastika'],
        'description': 'Психологический триллер о писателе, попавшем в плен к своей одержимой поклоннице. Один из самых напряжённых романов Кинга.',
        'price': 560,
        'stock': 13,
        'pages': 448,
        'year_published': 1987,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-119745-5',
        'featured': False,
    },
    {
        'title': 'Гарри Поттер и философский камень',
        'slug': 'garri-potter-filosofsky-kamen',
        'author': authors['Джоан Роулинг'],
        'category': categories['detskaya-literatura'],
        'description': 'Первая книга серии о молодом волшебнике Гарри Поттере. История о дружбе, магии и борьбе добра со злом.',
        'price': 590,
        'stock': 30,
        'pages': 432,
        'year_published': 1997,
        'publisher': 'РОСМЭН',
        'language': 'Русский',
        'isbn': '978-5-353-01435-6',
        'featured': True,
    },
    {
        'title': 'Гарри Поттер и тайная комната',
        'slug': 'garri-potter-taynaya-komnata',
        'author': authors['Джоан Роулинг'],
        'category': categories['detskaya-literatura'],
        'description': 'Вторая книга серии. Гарри возвращается в Хогвартс, где начинают происходить загадочные нападения на учеников.',
        'price': 590,
        'stock': 25,
        'pages': 384,
        'year_published': 1998,
        'publisher': 'РОСМЭН',
        'language': 'Русский',
        'isbn': '978-5-353-01436-3',
        'featured': False,
    },
    {
        'title': 'Мастер и Маргарита',
        'slug': 'master-i-margarita',
        'author': authors['Михаил Булгаков'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Мистический роман о визите Воланда (дьявола) в советскую Москву. Одно из самых загадочных и глубоких произведений русской литературы XX века.',
        'price': 530,
        'stock': 18,
        'pages': 480,
        'year_published': 1967,
        'publisher': 'Эксмо',
        'language': 'Русский',
        'isbn': '978-5-04-099876-3',
        'featured': True,
    },
    {
        'title': 'Собачье сердце',
        'slug': 'sobache-serdce',
        'author': authors['Михаил Булгаков'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Сатирическая повесть о профессоре Преображенском, пересадившем человеческий гипофиз бездомной собаке. Острая критика советского общества.',
        'price': 380,
        'stock': 16,
        'pages': 224,
        'year_published': 1925,
        'publisher': 'Эксмо',
        'language': 'Русский',
        'isbn': '978-5-04-099878-7',
        'featured': False,
    },
    {
        'title': 'Белый пароход',
        'slug': 'belyy-parohod',
        'author': authors['Чингиз Айтматов'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Повесть выдающегося кыргызского писателя о мальчике, живущем в горном урочище, и его мечтах. Глубокое размышление о добре и жестокости мира.',
        'price': 350,
        'stock': 12,
        'pages': 184,
        'year_published': 1970,
        'publisher': 'Кыргызстан',
        'language': 'Русский',
        'isbn': '978-5-000-00001-0',
        'featured': True,
    },
    {
        'title': 'Джамиля',
        'slug': 'dzhamilya',
        'author': authors['Чингиз Айтматов'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Повесть о любви молодой кыргызской женщины. Луи Арагон назвал её "самой прекрасной повестью о любви в мировой литературе".',
        'price': 300,
        'stock': 14,
        'pages': 96,
        'year_published': 1958,
        'publisher': 'Кыргызстан',
        'language': 'Русский',
        'isbn': '978-5-000-00002-7',
        'featured': False,
    },
    {
        'title': 'Плаха',
        'slug': 'plaha',
        'author': authors['Чингиз Айтматов'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Роман о нравственном выборе человека, браконьерстве и наркоторговле в советском обществе. Один из самых острых романов Айтматова.',
        'price': 420,
        'stock': 10,
        'pages': 304,
        'year_published': 1986,
        'publisher': 'Кыргызстан',
        'language': 'Русский',
        'isbn': '978-5-000-00003-4',
        'featured': False,
    },
    {
        'title': 'На Западном фронте без перемен',
        'slug': 'na-zapadnom-fronte-bez-peremen',
        'author': authors['Эрих Мария Ремарк'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Антивоенный роман о немецких солдатах Первой мировой войны. Одно из самых пронзительных произведений о войне в мировой литературе.',
        'price': 420,
        'stock': 14,
        'pages': 304,
        'year_published': 1929,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-088034-2',
        'featured': False,
    },
    {
        'title': 'Три товарища',
        'slug': 'tri-tovarischa',
        'author': authors['Эрих Мария Ремарк'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Роман о дружбе трёх ветеранов Первой мировой и любви на фоне Германии 1920-х годов. Один из самых трогательных романов Ремарка.',
        'price': 450,
        'stock': 12,
        'pages': 384,
        'year_published': 1936,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-088035-9',
        'featured': True,
    },
    {
        'title': 'Вишнёвый сад',
        'slug': 'vishnyovy-sad',
        'author': authors['Антон Чехов'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Последняя пьеса Чехова — лирическая комедия об уходящей эпохе дворянства и неизбежных переменах. Шедевр мировой драматургии.',
        'price': 320,
        'stock': 17,
        'pages': 112,
        'year_published': 1904,
        'publisher': 'Эксмо',
        'language': 'Русский',
        'isbn': '978-5-04-099879-4',
        'featured': False,
    },
    {
        'title': 'Палата №6 и другие рассказы',
        'slug': 'palata-nomer-6',
        'author': authors['Антон Чехов'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Сборник рассказов и повестей Чехова, включая "Палату №6" — историю о враче, оказавшемся в психиатрической больнице. Мастерство короткой формы.',
        'price': 360,
        'stock': 15,
        'pages': 320,
        'year_published': 1892,
        'publisher': 'Эксмо',
        'language': 'Русский',
        'isbn': '978-5-04-099880-0',
        'featured': False,
    },
    {
        'title': 'Евгений Онегин',
        'slug': 'evgeniy-onegin',
        'author': authors['Александр Пушкин'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Роман в стихах — энциклопедия русской жизни XIX века. История холодного петербургского франта и влюблённой в него провинциальной девушки.',
        'price': 380,
        'stock': 20,
        'pages': 240,
        'year_published': 1833,
        'publisher': 'Эксмо',
        'language': 'Русский',
        'isbn': '978-5-04-099881-7',
        'featured': True,
    },
    {
        'title': 'Капитанская дочка',
        'slug': 'kapitanskaya-dochka',
        'author': authors['Александр Пушкин'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Исторический роман о временах пугачёвского восстания. История любви и чести на фоне кровавых событий XVIII века.',
        'price': 290,
        'stock': 18,
        'pages': 176,
        'year_published': 1836,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-099125-1',
        'featured': False,
    },
    {
        'title': '1984',
        'slug': '1984-orwell',
        'author': authors['Джордж Оруэлл'],
        'category': categories['fantastika'],
        'description': 'Культовая антиутопия о тоталитарном обществе, где Большой Брат следит за каждым. Одна из самых влиятельных книг XX века.',
        'price': 490,
        'stock': 22,
        'pages': 320,
        'year_published': 1949,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-099126-8',
        'featured': True,
    },
    {
        'title': 'Скотный двор',
        'slug': 'skotny-dvor',
        'author': authors['Джордж Оруэлл'],
        'category': categories['fantastika'],
        'description': 'Политическая сатира-притча о животных, свергнувших хозяина фермы. Острая аллегория на советский тоталитаризм.',
        'price': 320,
        'stock': 19,
        'pages': 128,
        'year_published': 1945,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-099127-5',
        'featured': False,
    },
    {
        'title': 'Азазель',
        'slug': 'azazel-akunin',
        'author': authors['Борис Акунин'],
        'category': categories['detektivy'],
        'description': 'Первый роман о сыщике Эрасте Фандорине. Молодой чиновник расследует загадочные самоубийства в Москве 1876 года. Блестящий исторический детектив.',
        'price': 410,
        'stock': 16,
        'pages': 256,
        'year_published': 1998,
        'publisher': 'Захаров',
        'language': 'Русский',
        'isbn': '978-5-8159-0001-2',
        'featured': False,
    },
    {
        'title': 'Турецкий гамбит',
        'slug': 'turecky-gambit',
        'author': authors['Борис Акунин'],
        'category': categories['detektivy'],
        'description': 'Второй роман о Фандорине. Русско-турецкая война 1877 года, шпионаж и интриги. Увлекательный исторический детектив.',
        'price': 390,
        'stock': 14,
        'pages': 240,
        'year_published': 1998,
        'publisher': 'Захаров',
        'language': 'Русский',
        'isbn': '978-5-8159-0002-9',
        'featured': False,
    },
    {
        'title': 'Старик и море',
        'slug': 'starik-i-more',
        'author': authors['Эрнест Хемингуэй'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Повесть о старом кубинском рыбаке и его схватке с огромным марлином. За неё Хемингуэй получил Нобелевскую премию по литературе.',
        'price': 360,
        'stock': 20,
        'pages': 128,
        'year_published': 1952,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-099128-2',
        'featured': True,
    },
    {
        'title': 'По ком звонит колокол',
        'slug': 'po-kom-zvonit-kolokol',
        'author': authors['Эрнест Хемингуэй'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Роман об американском добровольце, воюющем на стороне республиканцев в Испании. История любви и самопожертвования на фоне гражданской войны.',
        'price': 520,
        'stock': 11,
        'pages': 480,
        'year_published': 1940,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-099129-9',
        'featured': False,
    },
    {
        'title': 'Превращение',
        'slug': 'prevraschenie-kafka',
        'author': authors['Франц Кафка'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Знаменитая повесть о коммивояжёре Грегоре Замза, проснувшемся однажды утром огромным насекомым. Символ отчуждения человека в современном мире.',
        'price': 310,
        'stock': 15,
        'pages': 96,
        'year_published': 1915,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-099130-5',
        'featured': False,
    },
    {
        'title': 'Процесс',
        'slug': 'process-kafka',
        'author': authors['Франц Кафка'],
        'category': categories['klassicheskaya-literatura'],
        'description': 'Роман о банковском служащем Йозефе К., арестованном без объяснения причин. Абсурдный судебный процесс как метафора бюрократии и бессилия человека.',
        'price': 380,
        'stock': 12,
        'pages': 272,
        'year_published': 1925,
        'publisher': 'АСТ',
        'language': 'Русский',
        'isbn': '978-5-17-099131-2',
        'featured': False,
    },
]

for data in books_data:
    book, created = Book.objects.get_or_create(slug=data['slug'], defaults=data)
    print(f"  {'Создана' if created else 'Уже есть'}: {data['title']}")

print("\n" + "="*50)
print("База данных успешно заполнена!")
print("="*50)
print(f"\nКатегорий: {Category.objects.count()}")
print(f"Авторов:   {Author.objects.count()}")
print(f"Книг:      {Book.objects.count()}")
print(f"\nАдмин-панель: /admin/")
print(f"Логин: admin | Пароль: admin123")